<?php

define('URL_BASE', $_SERVER['REQUEST_SCHEME'] . '://' . $_SERVER['HTTP_HOST'] . '/bt9fs3');
define('URL_STYLESHEET', URL_BASE . '/css/style.css');
define('DATA_DUTIES', 'data/duties.txt');
define('DATA_USERS', 'data/users.txt');
define('FILE_SVG_LOGO', 'svg/logo.svg');
define('FILE_SVG_PRIORITY', 'svg/priority.svg');
define('ICON_MENU', 'svg/menu.svg');
define('ID_NAV', 'navigation');
define('KEY_DUTY_BODY', 'body');
define('KEY_DUTY_IS_DONE', 'done');
define('KEY_DUTY_PRIORITY', 'priority');
define('KEY_DUTY_TIME', 'time');
define('KEY_DUTY_TITLE', 'title');
define('KEY_USER_ABOUT', 'about');
define('KEY_USER_EMAIL', 'email');
define('KEY_USER_NAME', 'name');
define('KEY_USER_PASSWORD', 'password');
define('KEY_USER_PASSWORD_AGAIN', 'password-again');
define('KEY_USER_ROLE', 'role');
define('KEY_USER_TERMS', 'terms');
define('LABEL_PAGE_404', 'Page not found');
define('LABEL_PAGE_ADD', 'Add new');
define('LABEL_PAGE_DUTIES', 'Duties');
define('LABEL_PAGE_HOME', 'Home');
define('LABEL_PAGE_LOGIN', 'Login');
define('LABEL_PAGE_LOG_OUT', 'Log out');
define('LABEL_PAGE_REGISTRATION', 'Registration');
define('P', 'agenda');
define('PAGE_404', '404.php');
define('PAGE_ADD', 'duty.php');
define('PAGE_DUTIES', 'duties.php');
define('PAGE_HOME', 'index.php');
define('PAGE_LOGIN', 'login.php');
define('PAGE_LOG_OUT', 'logout.php');
define('PAGE_REGISTRATION', 'registration.php');
define('PROPERTY_DUTY_BODY', 'body');
define('PROPERTY_DUTY_IS_DONE', 'done');
define('PROPERTY_DUTY_PRIORITY', 'priority');
define('PROPERTY_DUTY_TIME', 'time');
define('PROPERTY_DUTY_TITLE', 'title');
define('PROPERTY_ICON', 'icon');
define('PROPERTY_IS_MAIN', 'isMain');
define('PROPERTY_IS_MESSAGE_PRIVATE', 'isMessagePrivate');
define('PROPERTY_MESSAGES', 'messages');
define('PROPERTY_TYPE', 'type');
define('PROPERTY_VALUE', 'value');
define('ROLE_ADMIN', 'admin');
define('ROLE_REVISOR', 'revisor');
define('ROLE_USER', 'user');
define('SESSION_MESSAGES', 'messages');
define('SESSION_USER_ROLE', 'user-role');
define('SESSION_USER_NAME', 'user-name');
define('SESSION_USER_TIMEOUT', 'user-timeout');
define('TYPE_MESSAGE_ERROR', 'error');
define('TYPE_MESSAGE_INFO', 'info');
define('TYPE_MESSAGE_NEUTRAL', 'neutral');
define('TYPE_MESSAGE_SUCCESS', 'success');
define('TYPE_MESSAGE_WARNING', 'warning');
define('VALUE_CHECKBOX_TRUE', 'true');
define('VALUE_PRIORITY_NEGLIGIBLE', 'negligible');
define('VALUE_PRIORITY_MODERATE', 'moderate');
define('VALUE_PRIORITY_IMPORTANT', 'important');
define('VALUE_PRIORITY_URGENT', 'urgent');
define('VALUE_PRIORITY_CRITICAL', 'critical');
